MIM-2040-Breadcrumb-mobileCompressedView
statisticsnorway/ssb-component-library pull request #1363
Opened 2024-11-04 11:24 UTC by Carl-OW

2024-11-04 11:46 UTC, johnnadeluy commented on src/components/Breadcrumb/index.jsx
> +          <span
Sonarcloud Error:
Use <input aria-pressed=...>, <summary aria-expanded="false">, <summary aria-expanded="true">, <input type="button">, <input type="image">, <input type="reset">, <input type="submit">, or <button> instead of the "button" role to ensure accessibility across all devices.

2024-11-04 11:47 UTC, johnnadeluy commented on package-lock.json
> +  "version": "2.3.2",
The newest version is 2.3.3. Remember to bump `package.json` to 2.3.4 after merge from master.

2024-11-04 11:52 UTC, johnnadeluy commented on src/components/Breadcrumb/_breadcrumb.scss
> +.focus-outline:focus {
Is it supposed to look like this?
![image](https://github.com/user-attachments/assets/651a5489-9f4e-435a-a1f9-eb4ba4299b6d)

2024-11-04 11:55 UTC, johnnadeluy commented on src/components/Breadcrumb/index.jsx
> +    const handleResize = () => setIsMobile(window.innerWidth < 600)
Suggestion: `767` max width instead of `600`.
This is from the viewport `$mobile` variable we use for the component library.

2024-11-04 11:59 UTC, johnnadeluy requested changes
Remember to also update the Breadcrumb component documentation:
https://github.com/statisticsnorway/ssb-component-library/blob/master/src/components/Breadcrumb/README.md

It would also be nice if the storybook examples were updated with a new example for the compressed mobile view.

2024-11-04 13:22 UTC, Carl-OW commented on src/components/Breadcrumb/_breadcrumb.scss
> +.focus-outline:focus {
QA-forretning får se på dette, skal informere de

2024-11-04 14:25 UTC, johnnadeluy commented on src/components/Breadcrumb/breadcrumb.story.jsx
> +    <p>mobileCompressedView :</p>
Suggestion: Render the example in a separate const instead of adding text directly to describe the difference so that it's consistent with how it's done for every other components e.g. https://github.com/statisticsnorway/ssb-component-library/blob/master/src/components/Accordion/accordion.story.jsx

2024-11-04 14:32 UTC, johnnadeluy commented on package.json
> +  "version": "2.3.4",
This should probably be `2.4.0` instead since it's a new feature. My bad!

2024-11-05 07:31 UTC, johnnadeluy approved these changes
Good job 🎖

2024-11-05 08:03 UTC, merged